[package]
name = "thar-be-settings"
version = "0.1.0"
authors = ["Zac Mrowicki <mrowicki@amazon.com>"]
license = "Apache-2.0 OR MIT"
edition = "2018"
publish = false
build = "build.rs"
# Don't rebuild crate just because of changes to README.
exclude = ["README.md"]

[dependencies]
apiclient = { path = "../apiclient" }
handlebars = "3.0"
http = "0.2"
itertools = "0.10"
log = "0.4"
models = { path = "../../models" }
schnauzer = { path = "../schnauzer" }
serde_json = "1"
simplelog = "0.9"
snafu = "0.6"
tokio = { version = "0.2", default-features = false, features = ["macros", "rt-threaded"] }
# When hyper updates to tokio 0.3:
#tokio = { version = "0.3", default-features = false, features = ["macros", "rt-multi-thread"] }

[build-dependencies]
cargo-readme = "3.1"

[dev-dependencies]
maplit = "1.0"