[package]
name = "acpid"
version = "0.1.0"
edition = "2018"
publish = false
build = "build.rs"

[lib]
path = "pkg.rs"

[package.metadata.build-package]
release-url = "http://downloads.sourceforge.net/acpid2"

[[package.metadata.build-package.external-files]]
url = "http://downloads.sourceforge.net/acpid2/acpid-2.0.33.tar.xz"
sha512 = "491a58c62fcad44dc57cbd9294437fbc215c2ec99a030286601cd1956ea504e723e61b11b315983073d66aace1997bc40e6421475f6073298f60b8dcda2add75"

[build-dependencies]
glibc = {path = "../glibc"}
