[package]
name = "kubernetes-1_19"
version = "0.1.0"
edition = "2018"
publish = false
build = "build.rs"

[lib]
path = "pkg.rs"

[package.metadata.build-package]
package-name = "kubernetes-1.19"
releases-url = "https://github.com/kubernetes/kubernetes/releases"

[[package.metadata.build-package.external-files]]
url = "https://github.com/kubernetes/kubernetes/archive/v1.19.16/kubernetes-1.19.16.tar.gz"
sha512 = "1d8c082bd90f27d149cd0575911647749ed7baf17215aaa29ef01421fc1cbabb6dbc8d2dd61c023465d87c61854bd2f1ed941e91941f4e3667b49595a00e46f6"

[build-dependencies]
glibv = { path = "../glibc" }

[depencies]
# `containered`

