[package]
name = "docker-cli"
version = "0.1.0"
edition = "2018"
publish = false
build = "build.rs"

[lib]
path = "pkg.rs"

[[package.metadata.build-package.external-files]]
url = "https://github.com/docker/cli/archive/v18.09.6/cli-18.09.6.tar.gz"
sha512 = "c2621391c3848cf348f7a719e72c07cb4c7e7d20ba3529a0ec188270b02d6b0e1fdea47b6a61a09228e98f1ebbe0f36e789821ff06dcd30cb17a9c4541b3d444"

[build-dependencies]
buildsys = { path = "../../tools/buildsys" }
glibc = { path = "../glibc", optional=true }
golang = { path = "../golang", optional=true }

[features]
cascade = [
    "glibc",
    "golang",
]
