[package]
name = "ssm"
version = "0.1.0"
edition = "2018"
publish = false
build = "build.rs"

[lib]
path = "pkg.rs"

[[package.metadata.build-package.external-files]]
url = "https://github.com/aws/amazon-ssm-agent/archive/2.3.672.0/amazon-ssm-agent-2.3.672.0.tar.gz"
sha512 = "8f8f2ecc3f5f34f2d01da451c18f0312d4772ee92b63699ee135777003c8006a46c4bf9a5d187f71b904e2ae4beb203de92e4c4d922febf01b1faa07e60031a9"

[build-dependencies]
buildsys = { path = "../../tools/buildsys" }
glibc = { path = "../glibc", optional=true }
golang = { path = "../golang", optional=true }

[features]
cascade = [
    "glibc",
    "golang",
]
