[package]
name = "cni"
version = "0.1.0"
edition = "2018"
publish = false
build = "build.rs"

[lib]
path = "pkg.rs"

[[package.metadata.build-package.external-files]]
url = "https://github.com/containernetworking/cni/archive/v0.7.1/cni-0.7.1.tar.gz"
sha512 = "ca97ad8cd693a50c7c793266e23c2c38c4cb6917dc38c68f88921f48daf437375aa2d347eba70c8dc4e08ba6e6f008e0164282029fa36aab98417e763eb29285"

[build-dependencies]
buildsys = { path = "../../tools/buildsys" }
glibc = { path = "../glibc", optional=true }
golang = { path = "../golang", optional=true }

[features]
cascade = [
    "glibc",
    "golang",
]
