[package]
name = "util-linux"
version = "0.1.0"
edition = "2018"
publish = false
build = "build.rs"

[lib]
path = "pkg.rs"

[[package.metadata.build-package.external-files]]
url = "https://www.kernel.org/pub/linux/utils/util-linux/v2.33/util-linux-2.33.1.tar.xz"
sha512 = "94ada47e472b62a612c26fd5a5b7423e09366690a8a96f777191a5d920981eb0f224474bc2f128e827299bf60062770011332757e1551a8cd3764b5c70ae4ba2"

[build-dependencies]
buildsys = { path = "../../tools/buildsys" }
glibc = { path = "../glibc", optional=true }
libacl = { path = "../libacl", optional=true }
libxcrypt = { path = "../libxcrypt", optional=true }
ncurses = { path = "../ncurses", optional=true }

[features]
cascade = [
    "glibc",
    "libacl",
    "libxcrypt",
    "ncurses",
]
