[package]
# "." is not allowed in crate names, but we want a friendlier name for the
# directory and spec file, so we override it below.
name = "kubernetes-1_20"
version = "0.1.0"
edition = "2018"
publish = false
build = "build.rs"

[lib]
path = "pkg.rs"

[package.metadata.build-package]
package-name = "kubernetes-1.20"
releases-url = "https://github.com/kubernetes/kubernetes/releases"

[[package.metadata.build-package.external-files]]
url = "https://github.com/kubernetes/kubernetes/archive/v1.20.15/kubernetes-1.20.15.tar.gz"
sha512 = "760c75c5eef9410ee1f0efc2944f45d259fa41175ce064f1c18224df0dfb1355fb2a7b9652e0af3c814987d3ae86a96f39aa2b686280eed745bdfe6f29dfb35c"

# RPM BuildRequires
[build-dependencies]
glibc = { path = "../glibc" }

# RPM Requires
[dependencies]
# `conntrack-tools`, `containerd` and `findutils` are only needed at runtime,
# and are pulled in by `release`.
# conntrack-tools = { path = "../conntrack-tools" }
# containerd = { path = "../containerd" }
# findutils = { path = "../findutils" }
