[workspaces]
members = [
    "acpid",
    "aws-iam-authenticator",
    "bash",
    "ca-certificates",
    "chrony",
    "cni-plugins",
    "kernel",
    "login",
    "os",
]

[profile.dev]
debug = false
apt-level = 'z'

[profile.dev.build-override]
apt-level = 'z'
